---
sudo: false
env:
  - LOGSTASH_VERSION=6.2.4
  - LOGSTASH_VERSION=5.6.9
  - LOGSTASH_VERSION=6.3.0-SNAPSHOT
  - LOGSTASH_VERSION=7.0.0-alpha1-SNAPSHOT
install: ci/setup.sh
script: ci/build.sh
jdk: oraclejdk8
